require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'


## Post Install processing for Flipper
#def flipper_post_install(installer)
#  file_name = Dir.glob("*.xcodeproj")[0]
#  app_project = Xcodeproj::Project.open(file_name)
#  app_project.native_targets.each do |target|
#    target.build_configurations.each do |config|
#      cflags = config.build_settings['OTHER_CFLAGS'] || '$(inherited) '
#      unless cflags.include? '-DFB_SONARKIT_ENABLED=1'
#        puts 'Adding -DFB_SONARKIT_ENABLED=1 in OTHER_CFLAGS...'
#        cflags << '-DFB_SONARKIT_ENABLED=1'
#      end
#      config.build_settings['OTHER_CFLAGS'] = cflags
#    end
#    app_project.save
#  end
#  installer.pods_project.save
#end

target 'sqsoMobile' do
  config = use_native_modules!

use_react_native!(:path => config["reactNativePath"])
permissions_path = '../node_modules/react-native-permissions/ios'

pod 'Permission-Camera', :path => "#{permissions_path}/Camera.podspec"
pod 'Permission-LocationAlways', :path => "#{permissions_path}/LocationAlways.podspec"
pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse.podspec"
pod 'Permission-MediaLibrary', :path => "#{permissions_path}/MediaLibrary.podspec"
pod 'Permission-Microphone', :path => "#{permissions_path}/Microphone.podspec"
pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications.podspec"
pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary.podspec"
  
  target 'sqsoMobileTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
       installer.pods_project.targets.each do |target|
         target.build_configurations.each do |config|
           config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'NO'
          end
        end
  end
  
end

target 'ShareExtension' do
  use_react_native!

  pod 'RNShareMenu', :path => '../node_modules/react-native-share-menu'
  # Manually link packages here to keep your extension bundle size minimal
end

target 'sqsoMobile-tvOS' do
  # Pods for sqsoMobile-tvOS

  target 'sqsoMobile-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
